# Generated by Django 5.1 on 2025-03-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='installation_status',
            field=models.CharField(default='Not Installed', max_length=50),
        ),
    ]
