# Generated by Django 5.1 on 2025-03-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_module_installation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='delete_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='install_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
